### ISSUE TITLE
Linak Bluetooth Adapter

### ISSUE THREAD

**Issue by siers** [newAM/idasen#120]
Hi! I have a standing desk with a Linak controller, but it doesn't have bluetooth. However, I can buy an [Bluetooth® Adapter BLE2LIN002](https://www.linak.com/products/accessories/bluetooth-adapter-bed/#/description) for it. Should it also work with this application? I am running Linux, so I'd like to know before I'm going to buy it. :)

Thank you!

**Comment by newAM** [comment]
Unfortunately I am not sure about that one, mine had Bluetooth built-in.

Maybe send an email to linak support asking if it will work with your desk + the official app?  If it works with the app it will work with this.

**Comment by siers** [comment]
It should work with the app, apparently. Closing then.

**Comment by siers** [comment]
I can confirm it works! I had to restart the Linak module a few times and in the manual it says it only tries to pair within the first three minutes, which was important to me, as I plugged it in and forgot about it.

The module is quite hard to obtain, however, because Linak doesn't sell it directly and only a handful of suppliers are reselling it. Those who were either didn't ship outside their country or did so for slightly ridiculous prices. In the end I managed to get it for basically no shipping by making use of my extended social network. :clown_face:

**Comment by goldjunge91** [comment]
> Hi! I have a standing desk with a Linak controller, but it doesn't have bluetooth. However, I can buy an [Bluetooth® Adapter BLE2LIN002](https://www.linak.com/products/accessories/bluetooth-adapter-bed/#/description) for it. Should it also work with this application? I am running Linux, so I'd like to know before I'm going to buy it. :)
> 
> Thank you!

hi,
i have second hand buyed  lift desk with linak system motion system, and i have the controler "CBD6SP00020A-009"  and if my research is correct i can use the  [BLE2LIN002 ](https://lineardirect.eu/Linak-Bluetooth-Adapter-Desk-BLE2LIN002-Stick-HB11-Vollversion/BLE2LIN002),
I'm lucky i can get it for 40€ but as i see my control panel with 4 wires, as i look at the connector i can't imagine it's that hard to build something myself with an esp32. 
is it worth the effort or should i just buy the adapter ?

**Comment by siers** [comment]
Hi, personally, I just bought the adapter. Of course, you can in theory
make your own. Best of luck.

**Comment by Ordspilleren** [comment]
@goldjunge91 I managed to build a controller using an ESP32 and a simple circuit. You can find it here: https://github.com/Ordspilleren/esp32-linak-desk-control.

If course it is a bit involved, but certainly possible!

**Comment by goldjunge91** [comment]
> @goldjunge91 I managed to build a controller using an ESP32 and a simple circuit. You can find it here: https://github.com/Ordspilleren/esp32-linak-desk-control.
> 
> If course it is a bit involved, but certainly possible!

Ohh soo nice.
And i can not understand why google never show me you project, i have 100% search for "esp linak control", "esp desk linak control, really bad.
I was lucky on "kleinanzeigen.de" there was a guy that sell it for 12€ :D.
But thanks for sharing it.

Offtopic:
anyone a good supplier for spareparts ? i need the bracket from the motor inside maybe with motor,right now i got it repair with glue, and duck tape
