### ISSUE TITLE
Long execution time

### ISSUE THREAD

**Issue by bilbobag** [newAM/idasen#13]
Hey.

Thank you for great package. This issue isn't issue per se. I want to ask you guys how long is your execution time? I'm kind of worried because on my computer it takes around 20 seconds to execute a command, even if it's simple 'idasen height'. I can somehow live with that but I wonder if there is anything I can do to speed that up?

Thanks

**Comment by newAM** [comment]
What OS are you running and what bluetooth adapter do you have?

`bleak` is pretty slow to connect, but 20s is way too long.

Also, can you get a log with verbose logging?
`idasen height -vvvv`

**Comment by bilbobag** [comment]
I'm using Windows and connecting straight to laptop's BT. I believe it's some basic Intel(R) Wireless Bluetooth(R).
When I tried logging `idasen height -vvvv` it again took +/- 20 sec to start but the command finished relatively quickly. I guess there is a problem that my computer takes long to run the command, not the command itself.
`
DEBUG asyncio Using proactor: IocpProactor
DEBUG bleak.backends.dotnet.scanner Received E7:0A:DA:20:69:14: Unknown.
DEBUG bleak.backends.dotnet.scanner Received E7:0A:DA:20:69:14: Desk 6900.
DEBUG bleak.backends.dotnet.client Connecting to BLE device @ E7:0A:DA:20:69:14
DEBUG bleak.backends.dotnet.client _ConnectionStatusChanged_Handler: 1
DEBUG bleak.backends.dotnet.client Get Services...
INFO bleak.backends.dotnet.client Services resolved for BleakClientDotNet (E7:0A:DA:20:69:14)
DEBUG bleak.backends.dotnet.client Read Characteristic 99fa0021-338a-1024-8a49-009c0215f78a : bytearray(b'x\x13\x00\x00')
1.118 meters
DEBUG bleak.backends.dotnet.client Disconnecting from BLE device...
DEBUG bleak.backends.dotnet.client _ConnectionStatusChanged_Handler: 0`

**Comment by bilbobag** [comment]
I tried running `node` in the console. It also took more than 20s. I'm positive it's problem with my CMD so I'm okay with that if you want to close this issue. However, if anyone could help me with this, I would be so so happy!

Here is timing of `idasen height`

![image](https://user-images.githubusercontent.com/22870765/101260363-9c49b980-372f-11eb-971f-9a3484c542f9.png)

**Comment by newAM** [comment]
> I'm positive it's problem with my CMD so I'm okay with that if you want to close this issue.

Yikes!  I have had this happen once before in Windows, but I forget how I solved it, probably means it was just fixed with a reboot.

Best of luck!
