### ISSUE TITLE
Possibility of unpinning requirements max version?

### ISSUE THREAD

**Issue by abmantis** [newAM/idasen#344]
As mentioned a while ago, I am using this library as a dependency for an Home Assistant integration. 
During review, the current pinning of dependencies (specially bleak) came up as a concern, as it would prevent Home Assistant to jump to the latest version of bleak without also updating this library (and the integration dependency version). See https://github.com/home-assistant/core/pull/99173#issuecomment-1704462012 for context.

Would it be OK to remove the upper version pinning? Do you have any other suggestion on how to solve this?
As an alternative last resort, I can also fork this to make it more friendlier to HA, but I would prefer not to.

Let me know your thoughts on this!

**Comment by newAM** [comment]
Sure, I pin the version to prevent it breaking on new versions of bleak that contain breaking changes, but that doesn't happen often and I can understand how it is beneficial from a package maintenance perspective to have it unpinned.

**Comment by abmantis** [comment]
Cool! I will submit a PR with the change then. 
Thank you!
