### ISSUE TITLE
Superfluous dependencies?

### ISSUE THREAD

**Issue by blackcoffeerider** [newAM/idasen#8]
I dont fully understand several dependencies in the poetry build process and the installation.

Why are the following tools needed:
six        <= code is pure python 3.8?
twisted <= code uses asyncio?
constantly
zope.interface
pyhamcrest
hyperlink
Automat - (but thank you for using this because it is quiet interesting :) )
attrs (same as automat)

Not that they are bad to have but diskspace and cpu power is sparse on a raspberry pi zero :)
I don't know anything about the internals on how poetry works so before messing around with it to maybe clean it up myself i just wanted to know if these attempts would be futile because above dependencies are there for nonobvious reasons?

**Comment by newAM** [comment]
They're all comping from bleak (`poetry show --tree`).

```
bleak 0.9.1 Bluetooth Low Energy platform Agnostic Klient
├── pyobjc-core *
├── pyobjc-framework-corebluetooth *
│   ├── pyobjc-core >=6.2.2 
│   └── pyobjc-framework-cocoa >=6.2.2 
│       └── pyobjc-core >=6.2.2 (circular dependency aborted here)
├── pyobjc-framework-libdispatch *
│   └── pyobjc-core >=6.2.2 
├── pythonnet *
│   └── pycparser * 
└── txdbus *
    ├── six * 
    └── twisted >=10.1 
        ├── attrs >=19.2.0 
        ├── automat >=0.3.0 
        │   ├── attrs >=19.2.0 (circular dependency aborted here)
        │   └── six * (circular dependency aborted here)
        ├── constantly >=15.1 
        ├── hyperlink >=17.1.1 
        │   └── idna >=2.5 
        ├── incremental >=16.10.1 
        ├── pyhamcrest >=1.9.0,<1.10.0 || >1.10.0 
        └── zope.interface >=4.4.2 
```

**Comment by blackcoffeerider** [comment]
Well... i rest my case then and will live with the slight overhead :)
Thanks a million for this. I praised you here by the way: https://twitter.com/blackcoffeeride/status/1321858262703198208 - but wanted to be able to change the desk level without having my main machine even running - so i moved it to a pi-zero and it works flawlessly.

**Comment by blackcoffeerider** [comment]
Case closed :)
